### ISSUE TITLE
AndroidPermissions error in api < 31

### ISSUE THREAD

**Issue by excript** [Android-for-Python/Camera4Kivy#16]
When using camera4kivy in api versions < 31, an exception occurs when executing the class: ``AndroidPermissions``.

When I disable the permissions code, everything works perfectly, however, the way permission is being requested in api versions > 25 < 30, with me it is not working.

**Comment by Android-for-Python** [comment]
Well to narrow it down a bit https://github.com/Android-for-Python/Camera4Kivy#buildozerspec

Please show the actual error message.

**Comment by excript** [comment]
But if the activation code and camera manipulation works great, why demand such high requirements?

Wouldn't it be better to make the code usable by more people?

Could you tell me if using the camera code, without the initial permission code, works in previous versions of the api?

**Comment by Android-for-Python** [comment]
I hope you are not confusing Android device versions with app build api versions. The Preview Widget will not work with build api < 29 and in practice use at least 30, the Store currently requires 32 or 33. https://github.com/Android-for-Python/Android-for-Python-Users#androidapi . 

The minimum device version for c4k is Android 5 because it depend on Camerax https://developer.android.com/training/camerax/devices  see also https://github.com/Android-for-Python/Camera4Kivy#tested-examples-and-platforms

In general it is not a valid assumption that some app will be portable across Android build api versions. Because the Android api changes (notably there were storage changes around versions 29/30 and 32/33). Usually it is OK, but not always.

Examples are a snapshot of a functional configuration, randomly changing (for example) versions may not work. This is generally true, it is pilot error to expect otherwise. Which says nothing about the range of build api versions over which the example might work. 

If you are trying various api versions read this first https://github.com/Android-for-Python/Android-for-Python-Users#changing-buildozerspec

If you are having an issue with permissions, check in the Android documentation and see if they are available for your chosen build api version and device version. https://github.com/Android-for-Python/Android-for-Python-Users#manifest-permissions
